; DO NOT EDIT THIS FILE! IT WAS AUTOMATICALLY GENERATED BY
; lein-cljsbuild FROM THE FOLLOWING SOURCE FILE:
; file:/home/gaz/development/cloj/src/gaz/play.clj

;;
(ns gaz.play
  (:use [clojure.tools.namespace.repl :only (refresh)])
  (:gen-class))

(defn -main
  "play around in reply entry point"
  [& args]
  (println "hello here are"))

