; DO NOT EDIT THIS FILE! IT WAS AUTOMATICALLY GENERATED BY
; lein-cljsbuild FROM THE FOLLOWING SOURCE FILE:
; file:/home/gaz/development/cloj/src/gaz/test.clj


(ns gaz.crossover)

(defn test [] true)
